version: "3.3"
services:
  domoticz:
    build: ./domoticz
    image: localbuild/domoticz:august2021
    container_name: domoticz
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - domoticzUserdata:/opt/domoticz/userdata
    environment:
      - TZ=Europe/Berlin
  nodered:
    build: ./nodered
    image: localbuild/nodered:august2021
    container_name: nodered
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - noderedData:/data
    networks:
      - edge
  grafana:
    build: ./grafana
    image: localbuild/grafana:august2021
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafanaData:/var/lib/grafana influxdb:
    build: ./influx
    image: localbuild/influxdb:august2021
    container_name: influxdb
    restart: unless-stopped
    environment:
      INFLUXDB_DB: DBONE
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin_pass
      INFLUXDB_USER: user
      INFLUXDB_USER_PASSWORD: user_pass
    ports:
      - "8082:8082"
      - "8086:8086"
      - "8089:8089"
    volumes:
      - influxData:/var/lib/influxdb
    networks:
      - edge
  mosquitto:
    build: ./mosquitto
    image: localbuild/mosquitto:june2021
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    networks:
      - edge

#Create internal link network for Containers
  networks:
    edge:

#Create Volumes for persistent Storage
  volumes:
    grafanaData:
    noderedData:
    influxData:
    mosquittoLog:
    mosquittoData:
    mosquittoConfig:
    domoticzUserdata:
